version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Upgrade pip and setuptools
          command: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade setuptools
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Activate virtual environment
          command: source venv/bin/activate
      - run:
          name: Install build dependencies
          command: pip install build-essential python3-dev
      - python/install-packages
      - run:
          name: Run tests
          command: python manage.py test
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Add deploy steps here
      - run:
          name: Deploy to production
          command: ./deploy.sh
workflows:
  build-and-test:
    jobs:
      - test-python
      - deploy:
          requires:
            - test-python
