# Generated by Django 4.2.2 on 2023-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='dimensions',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_property',
            field=models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('commercial space', 'commercial space')], default='house', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mainimage',
            field=models.ImageField(default='none', upload_to='account/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subimage1',
            field=models.ImageField(default='none', upload_to='account/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subimage2',
            field=models.ImageField(default='none', upload_to='account/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subimage3',
            field=models.ImageField(default='none', upload_to='account/images'),
        ),
    ]
