# Generated by Django 3.2.4 on 2023-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0003_remove_profile_country_profile_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rooms',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
