# Generated by Django 3.2.4 on 2023-07-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0004_users_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rooms',
        ),
    ]
