# Generated by Django 3.2.4 on 2023-07-01 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jyore', '0005_remove_users_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_property',
            field=models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('commercial space', 'Commercial Space')], default='house', max_length=20),
        ),
    ]
