# Generated by Django 3.2.4 on 2023-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0009_rename_dimensions_profile_totalarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Willing_to',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='facing',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north-east', 'North-East'), ('north-west', 'North-West'), ('south-east', 'South-East'), ('south-west', 'South-West')], default='east', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
