# Generated by Django 3.2.4 on 2023-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0012_auto_20230708_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
    ]
