# Generated by Django 3.2.4 on 2023-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0013_remove_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
