# Generated by Django 3.2.4 on 2023-07-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0014_users_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
    ]
