# Generated by Django 3.2.4 on 2023-07-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0016_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp',
        ),
    ]
