# Generated by Django 3.2.4 on 2023-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0020_auto_20230709_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='price',
            new_name='age_of_property',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='length',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_of_property',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width',
        ),
        migrations.AddField(
            model_name='profile',
            name='ac',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chimney',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='dimensions_of_bedroom',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='dining_table',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='exhaust_fan',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='facing_road_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fans',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='flooring',
            field=models.CharField(choices=[('marble', 'Marble'), ('tiles', 'Tiles'), ('wooden', 'Wooden'), ('cement', 'Cement')], default='marble', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fridge',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='furnished',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gated_community',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='geysers',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gym',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='kitchen',
            field=models.CharField(choices=[('modular', 'Modular'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lift',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lights',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maintenance_staff',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='microwave',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_garden',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='rentprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sellprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sofa',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Ready to be occupied', 'Ready to be occupied'), ('In construction', 'In construction')], default='Ready to be occupied', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='swimming_pool',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tv',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='vasthu',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='wardrobe',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='washing_machine',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_purifier',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_source',
            field=models.CharField(choices=[('borewell', 'Borewell'), ('municipal', 'Municipal'), ('both', 'Both')], default='borewell', max_length=20),
        ),
    ]
