# Generated by Django 3.2.4 on 2023-07-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0023_auto_20230716_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facing_road_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rentprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sellprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
