# Generated by Django 3.2.4 on 2023-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0024_auto_20230716_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='internet',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rentprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sellprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
