# Generated by Django 3.2.4 on 2023-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0025_auto_20230716_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('land', 'Land')], default='house', max_length=20),
        ),
    ]
