# Generated by Django 3.2.4 on 2023-07-16 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jyore', '0026_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='landProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landlord_Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=30)),
                ('country', models.CharField(default='India', max_length=30)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('land_type', models.CharField(choices=[('corner', 'Corner'), ('gated community', 'Gated Community'), ('middle of the street', 'Middle of the street'), ('beside highway', 'Beside Highway')], default='corner', max_length=20)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('breadth', models.IntegerField(blank=True, null=True)),
                ('metric', models.CharField(choices=[('sq.m', 'Sq.m'), ('cents', 'Cents'), ('sq.ft', 'Sq.ft'), ('sq.yards', 'Sq.yards'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='sq.ft', max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Willing_to', models.CharField(choices=[('sell', 'Sell'), ('lease', 'Lease')], default='sell', max_length=20)),
                ('mainimage', models.ImageField(default='none', upload_to='account/images')),
                ('subimage1', models.ImageField(default='none', upload_to='account/images')),
                ('subimage2', models.ImageField(default='none', upload_to='account/images')),
                ('subimage3', models.ImageField(default='none', upload_to='account/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
