# Generated by Django 3.2.4 on 2023-07-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0027_landprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landprofile',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AlterField(
            model_name='landprofile',
            name='subimage1',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AlterField(
            model_name='landprofile',
            name='subimage2',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
        migrations.AlterField(
            model_name='landprofile',
            name='subimage3',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
    ]
