# Generated by Django 3.2.4 on 2023-07-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jyore', '0029_alter_landprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='landprofile',
            name='type',
            field=models.CharField(choices=[('land', 'Land'), ('house', 'House')], default='land', max_length=20),
        ),
    ]
